---
abstract: 'activate p2 extensions'
author:
  - 'Reini Urban <rurban@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: p2
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/perl11/p2-pragma
version: 0.02
